directory_path = "./files"

output_directory = "./output"
output_filename_format = "{output_directory}/{group2}/char_a_{group2}_{group3}_{group4}.png"
file_descriptions_filename = "{output_directory}/file_descriptions.json"

pattern = "^char_a_(p(?:\\d|BOW\\d|ONE\\d|POL\\d))_(\\d[a-z]{3})_([a-z0-9]{4})_(v\\d{2}).png$"

# Specify the output format as a flat list
output_format = [
    "p1",
    "p2",
    "p3",
    "p4",
    "pBOW1",
    "pBOW2",
    "pBOW3",
    "pBOW4",
    "pONE1",
    "pONE2",
    "pONE3",
    "pONE4",
    "pPOL1",
    "pPOL2",
    "pPOL3",
    "pPOL4",
]

# Or specify the output format as a matrix
# output_format = [
#   ["p1", "pBOW1", "pONE1", "pPOL1"],
#   ["p2", "pBOW2", "pONE2", "pPOL2"],
#   ["p3", "pBOW3", "pONE3", "pPOL3"],
#   ["p4", "pBOW4", "pONE4", "pPOL4"],
# ]
